services:
  # will create cluster with multiple ec2 instance (not dockerized) on production
  mongo-primary:
    container_name: mongo-primary
    image: mongo
    env_file:
      - ./.env
    expose:
      - 27017
    restart: always
    ports:
      - '30000:27017'
    volumes:
      - 'mongo-primary:/data/db/primary'
      - './rs-init.sh:/scripts/rs-init.sh'
      - './mkey.pem:/app/mkey.pem'
      - './.env:/app/.env'
    command: mongod --replSet mR0 --bind_ip_all --keyFile /app/mkey.pem

  mongo-secondary:
    container_name: mongo-secondary
    image: mongo
    env_file:
      - ./.env
    expose:
      - 27017
    restart: always
    ports:
      - '30001:27017'
    volumes:
      - 'mongo-secondary:/data/db/secondary'
      - './mkey.pem:/app/mkey.pem'
      - './.env:/app/.env'
    command: mongod --replSet mR0 --bind_ip_all --keyFile /app/mkey.pem

  mongo-arbiter:
    image: mongo
    container_name: mongo-arbiter
    env_file:
      - ./.env
    expose:
      - 27017
    restart: always
    ports:
      - '30002:27017'
    volumes:
      - 'mongo-arbiter:/data/db/arbiter'
      - './mkey.pem:/app/mkey.pem'
      - './.env:/app/.env'
    command: mongod --replSet mR0 --bind_ip_all --keyFile /app/mkey.pem

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    env_file:
      - ./.env
    command: ['yarn', 'start:dev']
    depends_on:
      - mongo-primary
      - mongo-secondary
      - mongo-arbiter
    volumes:
      - '.:/usr/src/app' #this is the purpose of mounting for dev, we'll mount other way for production
    ports:
      - '4000:4000'

volumes:
  mongo-primary:
    driver: local
  mongo-secondary:
    driver: local
  mongo-arbiter:
    driver: local
